# Generated by Django 5.0.1 on 2024-03-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_to_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('sub_heading', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Popular_destination_img/')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('days_nights', models.CharField(max_length=100)),
                ('pax', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('review_count', models.CharField(max_length=100)),
                ('stars', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='Photo_gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Popular_destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Popular_destination_img/')),
                ('city', models.CharField(max_length=200)),
                ('stars', models.PositiveIntegerField()),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
