# Generated by Django 5.0.1 on 2024-03-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_call_to_action_footer_packages_photo_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='sub_heading',
        ),
        migrations.RemoveField(
            model_name='photo_gallery',
            name='sub_heading',
        ),
        migrations.RemoveField(
            model_name='popular_destination',
            name='sub_heading',
        ),
    ]
